/***********************************************************************************************************************
 * app-global-ui.c
 * 
 * Copyright 2012 Axel FILMORE <axel.filmore@gmail.com>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License Version 2.
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * 
 * Purpose: LibFm's UI definitions.
 *          - EXEC_FILE_DLG     replaces exec-file.ui
 *          - APP_CHOOSER_DLG   replaces app-chooser.ui
 *          - RENAME_DLG        replaces ask-rename.ui
 *          - PROPERTIES_DLG    replaces file-prop.ui
 *          - APPLICATIONS_DLG  replaces 
 *          - PROGRESS_DLG      replaces progress.ui
 * 
 * Joke: In a lifter there's a fireman, Santa Claus, an intelligent woman and a dog, the dog is killed.
 * Who killed the dog ?
 * It's the fireman, that's obvious, Santa Claus doesn't exist, an intelligent woman doesn't exist, so it's the fireman.
 * 
 * :)
 * 
 **********************************************************************************************************************/


/***********************************************************************************************************************
 * Execute File Dialog
 * 
 * 
 **********************************************************************************************************************/
const char EXEC_FILE_DLG[] ="<?xml version='1.0'?>"
"<interface>"
"<requires lib='gtk+' version='2.16'/>"
"<!-- interface-naming-policy project-wide -->"
"<object class='GtkDialog' id='dlg'>"
"<property name='border_width'>5</property>"
"<property name='title' translatable='yes'>Execute File</property>"
"<property name='window_position'>center</property>"
"<property name='type_hint'>normal</property>"
"<property name='has_separator'>False</property>"
"<child internal-child='vbox'>"
"<object class='GtkVBox' id='dialog-vbox1'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>2</property>"
"<child>"
"<object class='GtkHBox' id='hbox1'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkImage' id='icon'>"
"<property name='visible'>True</property>"
"<property name='stock'>gtk-missing-image</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='msg'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child internal-child='action_area'>"
"<object class='GtkHButtonBox' id='dialog-action_area'>"
"<property name='visible'>True</property>"
"<property name='layout_style'>end</property>"
"<child>"
"<object class='GtkButton' id='exec'>"
"<property name='label'>gtk-execute</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='exec_term'>"
"<property name='label' translatable='yes'>Execute in _Terminal</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='open'>"
"<property name='label'>gtk-open</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='cancel'>"
"<property name='label'>gtk-cancel</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>3</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='pack_type'>end</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"<action-widgets>"
"<action-widget response='1'>exec</action-widget>"
"<action-widget response='2'>exec_term</action-widget>"
"<action-widget response='3'>open</action-widget>"
"<action-widget response='-7'>cancel</action-widget>"
"</action-widgets>"
"</object>"
"</interface>"
;


/***********************************************************************************************************************
 * Application Chooser Dialog
 * 
 * 
 **********************************************************************************************************************/
const char APP_CHOOSER_DLG[] ="<?xml version='1.0'?>"
"<interface>"
"<requires lib='gtk+' version='2.16'/>"
"<!-- interface-naming-policy toplevel-contextual -->"
"<object class='GtkDialog' id='dlg'>"
"<property name='border_width'>5</property>"
"<property name='title' translatable='yes'>Choose An Application</property>"
"<property name='default_width'>400</property>"
"<property name='default_height'>380</property>"
"<property name='type_hint'>dialog</property>"
"<property name='has_separator'>False</property>"
"<child internal-child='vbox'>"
"<object class='GtkVBox' id='dialog-vbox'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkHBox' id='file_type_hbox'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkLabel' id='label7'>"
"<property name='visible'>True</property>"
"<property name='xpad'>2</property>"
"<property name='ypad'>2</property>"
"<property name='label' translatable='yes'>&lt;b&gt;File Type To be Opened:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='file_type'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkNotebook' id='notebook'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<child>"
"<object class='GtkScrolledWindow' id='apps_scroll'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='hscrollbar_policy'>automatic</property>"
"<property name='vscrollbar_policy'>automatic</property>"
"<property name='shadow_type'>in</property>"
"<child>"
"<placeholder/>"
"</child>"
"</object>"
"</child>"
"<child type='tab'>"
"<object class='GtkLabel' id='label2'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>Installed Application</property>"
"</object>"
"<packing>"
"<property name='tab_fill'>False</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkVBox' id='vbox4'>"
"<property name='visible'>True</property>"
"<property name='border_width'>6</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label6'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Command line to execute:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkAlignment' id='alignment2'>"
"<property name='visible'>True</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkVBox' id='vbox5'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkHBox' id='hbox1'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkEntry' id='cmdline'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='invisible_char'>&#x25CF;</property>"
"<property name='activates_default'>True</property>"
"</object>"
"<packing>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='browse_btn'>"
"<property name='label' translatable='yes'>_Browse</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='image'>browse_btn_img</property>"
"<property name='use_underline'>True</property>"
"<signal name='clicked' handler='on_browse_btn_clicked' object='app_chooser_dlg'/>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkCheckButton' id='use_terminal'>"
"<property name='label' translatable='yes'>Execute in terminal emulator</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='use_underline'>True</property>"
"<property name='draw_indicator'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label5'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;These special codes can be used in the command line:&lt;/b&gt;"
"&lt;b&gt;%f&lt;/b&gt;: Represents a single file name"
"&lt;b&gt;%F&lt;/b&gt;: Represents multiple file names"
"&lt;b&gt;%u&lt;/b&gt;: Represents a single URI of the file"
"&lt;b&gt;%U&lt;/b&gt;: Represents multiple URIs</property>"
"<property name='use_markup'>True</property>"
"<property name='wrap'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child type='tab'>"
"<object class='GtkLabel' id='label3'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>Custom Command Line</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"<property name='tab_fill'>False</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='status'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkCheckButton' id='set_default'>"
"<property name='label' translatable='yes'>Set selected application as default action of this file type</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='use_underline'>True</property>"
"<property name='draw_indicator'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>3</property>"
"</packing>"
"</child>"
"<child internal-child='action_area'>"
"<object class='GtkHButtonBox' id='dialog-action_area1'>"
"<property name='visible'>True</property>"
"<property name='layout_style'>end</property>"
"<child>"
"<object class='GtkButton' id='cancelbutton'>"
"<property name='label'>gtk-cancel</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='okbutton'>"
"<property name='label'>gtk-ok</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='has_default'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='pack_type'>end</property>"
"<property name='position'>4</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"<action-widgets>"
"<action-widget response='-6'>cancelbutton</action-widget>"
"<action-widget response='-5'>okbutton</action-widget>"
"</action-widgets>"
"</object>"
"<object class='GtkImage' id='browse_btn_img'>"
"<property name='visible'>True</property>"
"<property name='stock'>gtk-open</property>"
"</object>"
"</interface>";


/***********************************************************************************************************************
 * Rename Dialog
 * 
 * 
 **********************************************************************************************************************/
const char RENAME_DLG[] ="<?xml version='1.0'?>"
"<interface>"
"<!-- interface-requires gtk+ 2.12 -->"
"<!-- interface-naming-policy toplevel-contextual -->"
"<object class='GtkDialog' id='dlg'>"
"<property name='border_width'>10</property>"
"<property name='title' translatable='yes'>Confirm to replace files</property>"
"<property name='type_hint'>normal</property>"
"<property name='has_separator'>False</property>"
"<child internal-child='vbox'>"
"<object class='GtkVBox' id='dialog-vbox'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkHBox' id='hbox'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkImage' id='image1'>"
"<property name='visible'>True</property>"
"<property name='yalign'>0</property>"
"<property name='stock'>gtk-dialog-question</property>"
"<property name='icon-size'>6</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkVBox' id='vbox1'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label1'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;There is already a file with the same name in this location.&lt;/b&gt;"
""
"Do you want to replace the existing file</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkHBox' id='hbox2'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkImage' id='dest_icon'>"
"<property name='visible'>True</property>"
"<property name='stock'>gtk-missing-image</property>"
"<property name='icon-size'>6</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='dest_fi'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label2'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>with the following file?</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkHBox' id='hbox3'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkImage' id='src_icon'>"
"<property name='visible'>True</property>"
"<property name='stock'>gtk-missing-image</property>"
"<property name='icon-size'>6</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='src_fi'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>3</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkHBox' id='hbox4'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkLabel' id='label3'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>File Name:</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkEntry' id='filename'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='invisible_char'>&#x2022;</property>"
"<property name='activates_default'>True</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>4</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkCheckButton' id='apply_all'>"
"<property name='label' translatable='yes'>Apply this option to all existing files</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='draw_indicator'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"<child internal-child='action_area'>"
"<object class='GtkHButtonBox' id='dialog-action_area'>"
"<property name='visible'>True</property>"
"<property name='layout_style'>end</property>"
"<child>"
"<object class='GtkButton' id='cancel'>"
"<property name='label'>gtk-cancel</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='skip'>"
"<property name='label' translatable='yes'>_Skip</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='has_default'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='rename'>"
"<property name='label' translatable='yes'>_Rename</property>"
"<property name='visible'>True</property>"
"<property name='sensitive'>False</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='overwrite'>"
"<property name='label' translatable='yes'>_Overwrite</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>3</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='pack_type'>end</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"<action-widgets>"
"<action-widget response='-6'>cancel</action-widget>"
"<action-widget response='3'>skip</action-widget>"
"<action-widget response='2'>rename</action-widget>"
"<action-widget response='1'>overwrite</action-widget>"
"</action-widgets>"
"</object>"
"</interface>";


/***********************************************************************************************************************
 * File Properties Dialog
 * 
 * 
 **********************************************************************************************************************/
const char PROPERTIES_DLG[] ="<?xml version='1.0'?>"
"<interface>"
"<requires lib='gtk+' version='2.16'/>"
"<!-- interface-naming-policy toplevel-contextual -->"
"<object class='GtkDialog' id='dlg'>"
"<property name='border_width'>6</property>"
"<property name='title' translatable='yes'>File Properties</property>"
"<property name='resizable'>False</property>"
"<property name='window_position'>center-on-parent</property>"
"<property name='default_width'>360</property>"
"<property name='type_hint'>dialog</property>"
"<property name='gravity'>center</property>"
"<property name='has_separator'>False</property>"
"<signal name='response' handler='on_filePropertiesDlg_response'/>"
"<child internal-child='vbox'>"
"<object class='GtkVBox' id='dialog_vbox'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkNotebook' id='notebook'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='border_width'>6</property>"
"<child>"
"<object class='GtkAlignment' id='alignment2'>"
"<property name='visible'>True</property>"
"<property name='top_padding'>6</property>"
"<property name='bottom_padding'>6</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkTable' id='general_table'>"
"<property name='visible'>True</property>"
"<property name='border_width'>4</property>"
"<property name='n_rows'>9</property>"
"<property name='n_columns'>2</property>"
"<property name='column_spacing'>12</property>"
"<property name='row_spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='type'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='xalign'>0</property>"
"<property name='wrap'>True</property>"
"<property name='selectable'>True</property>"
"<property name='ellipsize'>end</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>3</property>"
"<property name='bottom_attach'>4</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label4'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;File Type:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>3</property>"
"<property name='bottom_attach'>4</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label5'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Total Size of Files:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>5</property>"
"<property name='bottom_attach'>6</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label7'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Last Modification:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>7</property>"
"<property name='bottom_attach'>8</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='total_size'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='xalign'>0</property>"
"<property name='selectable'>True</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>5</property>"
"<property name='bottom_attach'>6</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='mtime'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='xalign'>0</property>"
"<property name='selectable'>True</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>7</property>"
"<property name='bottom_attach'>8</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label13'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Last Access:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>8</property>"
"<property name='bottom_attach'>9</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='atime'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>8</property>"
"<property name='bottom_attach'>9</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label20'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Location:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='dir'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='xalign'>0</property>"
"<property name='selectable'>True</property>"
"<property name='ellipsize'>middle</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkEntry' id='name'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label21'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Size on Disk:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>6</property>"
"<property name='bottom_attach'>7</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='size_on_disk'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='xalign'>0</property>"
"<property name='selectable'>True</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>6</property>"
"<property name='bottom_attach'>7</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='open_with_label'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Open _with:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"<property name='mnemonic_widget'>open_with</property>"
"</object>"
"<packing>"
"<property name='top_attach'>4</property>"
"<property name='bottom_attach'>5</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkComboBox' id='open_with'>"
"<property name='visible'>True</property>"
"<property name='tooltip_text' translatable='yes'>Select the application used to open files of this type </property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>4</property>"
"<property name='bottom_attach'>5</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='target_label'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Target:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>2</property>"
"<property name='bottom_attach'>3</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='target'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='xalign'>0</property>"
"<property name='selectable'>True</property>"
"<property name='ellipsize'>middle</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>2</property>"
"<property name='bottom_attach'>3</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkImage' id='icon'>"
"<property name='visible'>True</property>"
"<property name='stock'>gtk-missing-image</property>"
"<property name='icon-size'>6</property>"
"</object>"
"<packing>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"</object>"
"</child>"
"<child type='tab'>"
"<object class='GtkLabel' id='label1'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>_General</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='tab_fill'>False</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkAlignment' id='alignment1'>"
"<property name='visible'>True</property>"
"<property name='top_padding'>6</property>"
"<property name='bottom_padding'>6</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkVBox' id='vbox1'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkTable' id='table3'>"
"<property name='visible'>True</property>"
"<property name='border_width'>2</property>"
"<property name='n_rows'>2</property>"
"<property name='n_columns'>2</property>"
"<property name='column_spacing'>12</property>"
"<property name='row_spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='owner_label'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;_Owner:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='group_label'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;_Group:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkEntry' id='owner'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='invisible_char'>&#x2022;</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkEntry' id='group'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='invisible_char'>&#x2022;</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkFrame' id='frame1'>"
"<property name='visible'>True</property>"
"<property name='label_xalign'>0</property>"
"<property name='shadow_type'>none</property>"
"<child>"
"<object class='GtkAlignment' id='alignment3'>"
"<property name='visible'>True</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkTable' id='table1'>"
"<property name='visible'>True</property>"
"<property name='border_width'>6</property>"
"<property name='n_rows'>4</property>"
"<property name='n_columns'>2</property>"
"<property name='column_spacing'>12</property>"
"<property name='row_spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label6'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Owner:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label8'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Group:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label9'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Other:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>2</property>"
"<property name='bottom_attach'>3</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkComboBox' id='owner_perm'>"
"<property name='visible'>True</property>"
"<property name='tooltip_text' translatable='yes'>Operations that the owner of the file can do</property>"
"<property name='model'>access_model</property>"
"<child>"
"<object class='GtkCellRendererText' id='cellrenderertext1'/>"
"<attributes>"
"<attribute name='text'>0</attribute>"
"</attributes>"
"</child>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkComboBox' id='group_perm'>"
"<property name='visible'>True</property>"
"<property name='tooltip_text' translatable='yes'>Operations that users in the same group as the owner of the file can do</property>"
"<property name='model'>access_model</property>"
"<child>"
"<object class='GtkCellRendererText' id='cellrenderertext2'/>"
"<attributes>"
"<attribute name='text'>0</attribute>"
"</attributes>"
"</child>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkComboBox' id='other_perm'>"
"<property name='visible'>True</property>"
"<property name='tooltip_text' translatable='yes'>Operations that all other users can do</property>"
"<property name='model'>access_model</property>"
"<child>"
"<object class='GtkCellRendererText' id='cellrenderertext3'/>"
"<attributes>"
"<attribute name='text'>0</attribute>"
"</attributes>"
"</child>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>2</property>"
"<property name='bottom_attach'>3</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkCheckButton' id='exec'>"
"<property name='label' translatable='yes'>Make the file executable</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='draw_indicator'>True</property>"
"</object>"
"<packing>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>3</property>"
"<property name='bottom_attach'>4</property>"
"<property name='y_options'>GTK_FILL</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"</object>"
"</child>"
"<child type='label'>"
"<object class='GtkLabel' id='label3'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Access Control&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child type='tab'>"
"<object class='GtkLabel' id='label2'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>_Permissions</property>"
"<property name='use_underline'>True</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"<property name='tab_fill'>False</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"<child internal-child='action_area'>"
"<object class='GtkHButtonBox' id='dialog_action_area'>"
"<property name='visible'>True</property>"
"<property name='layout_style'>end</property>"
"<child>"
"<object class='GtkButton' id='cancel'>"
"<property name='label'>gtk-cancel</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='use_stock'>True</property>"
"<signal name='clicked' handler='gtk_widget_destroy' object='filePropertiesDlg'/>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='ok'>"
"<property name='label'>gtk-ok</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='has_default'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='use_stock'>True</property>"
"<signal name='clicked' handler='gtk_widget_destroy' object='filePropertiesDlg'/>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='pack_type'>end</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"<action-widgets>"
"<action-widget response='-6'>cancel</action-widget>"
"<action-widget response='-5'>ok</action-widget>"
"</action-widgets>"
"</object>"
"<object class='GtkListStore' id='access_model'>"
"<columns>"
"<!-- column-name Access -->"
"<column type='gchararray'/>"
"</columns>"
"<data>"
"<row>"
"<col id='0' translatable='yes'>Read and Write</col>"
"</row>"
"<row>"
"<col id='0' translatable='yes'>Read only</col>"
"</row>"
"<row>"
"<col id='0' translatable='yes'>Write only</col>"
"</row>"
"<row>"
"<col id='0' translatable='yes'>None</col>"
"</row>"
"<row>"
"<col id='0' translatable='yes'>---</col>"
"</row>"
"</data>"
"</object>"
"</interface>";


/***********************************************************************************************************************
 * Preferred Applications Dialog
 * 
 * 
 **********************************************************************************************************************/
const char APPLICATIONS_DLG[] ="<?xml version='1.0'?>"
"<interface>"
"<requires lib='gtk+' version='2.16'/>"
"<!-- interface-naming-policy project-wide -->"
"<object class='GtkDialog' id='dlg'>"
"<property name='border_width'>5</property>"
"<property name='title' translatable='yes'>Preferred Applications</property>"
"<property name='window_position'>center</property>"
"<property name='type_hint'>normal</property>"
"<property name='has_separator'>False</property>"
"<child internal-child='vbox'>"
"<object class='GtkVBox' id='dialog-vbox1'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>2</property>"
"<child>"
"<object class='GtkNotebook' id='notebook1'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<child>"
"<object class='GtkVBox' id='vbox1'>"
"<property name='visible'>True</property>"
"<property name='border_width'>12</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>18</property>"
"<child>"
"<object class='GtkVBox' id='vbox2'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label3'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Web Browser&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkAlignment' id='alignment1'>"
"<property name='visible'>True</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkVBox' id='vbox5'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label4'>"
"<property name='width_request'>360</property>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>The preferred Web Browser will be used to open hyperlinks.</property>"
"<property name='wrap'>True</property>"
"</object>"
"<packing>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkComboBox' id='browser'>"
"<property name='visible'>True</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkVBox' id='vbox3'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label5'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Mail client&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkAlignment' id='alignment2'>"
"<property name='visible'>True</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkVBox' id='vbox6'>"
"<property name='visible'>True</property>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label6'>"
"<property name='width_request'>360</property>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>The preferred Mail Client will be used to compose emails when you click on E-mail addresses.</property>"
"<property name='wrap'>True</property>"
"<property name='width_chars'>60</property>"
"</object>"
"<packing>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkComboBox' id='mail_client'>"
"<property name='visible'>True</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkVBox' id='vbox4'>"
"<property name='orientation'>vertical</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label7'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Terminal Emulator&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkAlignment' id='alignment3'>"
"<property name='visible'>True</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkHBox' id='hbox4'>"
"<property name='visible'>True</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label8'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>Command line:</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkEntry' id='terminal'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='invisible_char'>&#x2022;</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"<child type='tab'>"
"<object class='GtkLabel' id='label1'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>System Applications</property>"
"</object>"
"<packing>"
"<property name='tab_fill'>False</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkVBox' id='vbox8'>"
"<property name='orientation'>vertical</property>"
"<child>"
"<placeholder/>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child type='tab'>"
"<object class='GtkLabel' id='label2'>"
"<property name='visible'>True</property>"
"<property name='label' translatable='yes'>File Associations</property>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"<property name='tab_fill'>False</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child internal-child='action_area'>"
"<object class='GtkHButtonBox' id='dialog-action_area1'>"
"<property name='visible'>True</property>"
"<property name='layout_style'>end</property>"
"<child>"
"<object class='GtkButton' id='cancel'>"
"<property name='label'>gtk-cancel</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkButton' id='ok'>"
"<property name='label'>gtk-ok</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='receives_default'>True</property>"
"<property name='use_stock'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='pack_type'>end</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"<action-widgets>"
"<action-widget response='-6'>cancel</action-widget>"
"<action-widget response='-5'>ok</action-widget>"
"</action-widgets>"
"</object>"
"</interface>";


/***********************************************************************************************************************
 * Progress Dialog
 * 
 * 
 **********************************************************************************************************************/
const char PROGRESS_DLG[] ="<?xml version='1.0' encoding='UTF-8'?>"
"<interface>"
"<!-- interface-requires gtk+ 2.12 -->"
"<!-- interface-naming-policy toplevel-contextual -->"
"<object class='GtkDialog' id='dlg'>"
"<property name='visible'>True</property>"
"<property name='border_width'>5</property>"
"<property name='default_width'>480</property>"
"<property name='type_hint'>dialog</property>"
"<property name='gravity'>north-east</property>"
"<child internal-child='vbox'>"
"<object class='GtkVBox' id='dialog-vbox'>"
"<property name='visible'>True</property>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkVBox' id='vbox1'>"
"<property name='visible'>True</property>"
"<property name='border_width'>6</property>"
"<property name='spacing'>18</property>"
"<child>"
"<object class='GtkLabel' id='msg'>"
"<property name='xalign'>0</property>"
"<property name='wrap'>True</property>"
"</object>"
"<packing>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkHBox' id='hbox1'>"
"<property name='visible'>True</property>"
"<property name='spacing'>12</property>"
"<child>"
"<object class='GtkImage' id='icon'>"
"<property name='visible'>True</property>"
"<property name='stock'>gtk-file</property>"
"<property name='icon-size'>6</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkTable' id='table'>"
"<property name='visible'>True</property>"
"<property name='border_width'>6</property>"
"<property name='n_rows'>5</property>"
"<property name='n_columns'>2</property>"
"<property name='column_spacing'>12</property>"
"<property name='row_spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='src'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='ellipsize'>end</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='dest'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='ellipsize'>middle</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='current'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes' comments='Preparing to do some file operation (Copy, Move, Delete...) '>Preparing...</property>"
"<property name='ellipsize'>middle</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>2</property>"
"<property name='bottom_attach'>3</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkProgressBar' id='progress'>"
"<property name='visible'>True</property>"
"<property name='pulse_step'>0.10000000149</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>3</property>"
"<property name='bottom_attach'>4</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label4'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes' comments='Processing: &lt;Name of currently proccesed file&gt;'>&lt;b&gt;Processing:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>2</property>"
"<property name='bottom_attach'>3</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='to_label'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes' comments='To: &lt;Destination folder&gt; ex. Copy file to..., Move file to...etc.'>&lt;b&gt;To:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>1</property>"
"<property name='bottom_attach'>2</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label3'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Progress:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>3</property>"
"<property name='bottom_attach'>4</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='action'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='label2'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Time remaining:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='top_attach'>4</property>"
"<property name='bottom_attach'>5</property>"
"<property name='x_options'>GTK_FILL</property>"
"<property name='y_options'></property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkLabel' id='remaining_time'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"</object>"
"<packing>"
"<property name='left_attach'>1</property>"
"<property name='right_attach'>2</property>"
"<property name='top_attach'>4</property>"
"<property name='bottom_attach'>5</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkVBox' id='error_pane'>"
"<property name='spacing'>6</property>"
"<child>"
"<object class='GtkLabel' id='label1'>"
"<property name='visible'>True</property>"
"<property name='xalign'>0</property>"
"<property name='label' translatable='yes'>&lt;b&gt;Some errors occurred:&lt;/b&gt;</property>"
"<property name='use_markup'>True</property>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"<child>"
"<object class='GtkAlignment' id='alignment1'>"
"<property name='visible'>True</property>"
"<property name='left_padding'>12</property>"
"<child>"
"<object class='GtkScrolledWindow' id='scrolledwindow1'>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='hscrollbar_policy'>automatic</property>"
"<property name='vscrollbar_policy'>automatic</property>"
"<property name='shadow_type'>etched-in</property>"
"<child>"
"<object class='GtkTextView' id='error_msg'>"
"<property name='height_request'>120</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='cursor_visible'>False</property>"
"</object>"
"</child>"
"</object>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>2</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='position'>1</property>"
"</packing>"
"</child>"
"<child internal-child='action_area'>"
"<object class='GtkHButtonBox' id='dialog-action_area'>"
"<property name='visible'>True</property>"
"<property name='layout_style'>end</property>"
"<child>"
"<object class='GtkButton' id='cancel'>"
"<property name='label'>gtk-cancel</property>"
"<property name='visible'>True</property>"
"<property name='can_focus'>True</property>"
"<property name='can_default'>True</property>"
"<property name='receives_default'>False</property>"
"<property name='use_stock'>True</property>"
"<signal name='clicked' handler='on_cancel_button_clicked' object='fileOperation'/>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='fill'>False</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"</object>"
"<packing>"
"<property name='expand'>False</property>"
"<property name='pack_type'>end</property>"
"<property name='position'>0</property>"
"</packing>"
"</child>"
"</object>"
"</child>"
"<action-widgets>"
"<action-widget response='-6'>cancel</action-widget>"
"</action-widgets>"
"</object>"
"</interface>";


